version: '3.8'
services:
  acp-grpc-server:
    restart: unless-stopped
    image: ${IMAGE_NAME_PYACP:-ghcr.io/pyansys/pyacp-private:latest}
    environment:
      - ANSYSLMD_LICENSE_FILE=${ANSYSLMD_LICENSE_FILE}
    ports:
      - "${PORT_PYACP:-50555}:50051"
    working_dir: /home/container/workdir
    volumes:
      - "acp_data:/home/container/workdir/"
    user: "1000:1000"
  ansys-utilities-filetransfer:
    restart: unless-stopped
    image: ${IMAGE_NAME_FILETRANSFER:-ghcr.io/ansys/utilities-filetransfer:latest}
    ports:
      - "${PORT_FILETRANSFER:-50556}:50000"
    working_dir: /home/container/workdir
    volumes:
      - "acp_data:/home/container/workdir/"
    user: "1000:1000"
  mapdl:
    restart: unless-stopped
    image: ${IMAGE_NAME_MAPDL:-ghcr.io/pyansys/mapdl:latest}
    # By default, run on a single core only. Otherwise the command may
    # fail in restricted environments.
    # For example, the default Github Actions runner only has two cores.
    command: ${MAPDL_CMD:--smp -np 1}
    shm_size: '4gb'
    ports:
      - "${PORT_MAPDL:-50557}:50052"
    environment:
      - ANSYSLMD_LICENSE_FILE=${ANSYSLMD_LICENSE_FILE}
      - ANSYS_LOCK="OFF"
    # working directory is shared that the example also runs on Windows
    working_dir: /home/container/workdir
    volumes:
      - "acp_data:/home/container/workdir/"
  pydpf-composites-server:
    restart: unless-stopped
    image: ${IMAGE_NAME_DPF_COMPOSITES:-ghcr.io/pyansys/pydpf-composites:latest}
    ports:
      - "${PORT_DPF_COMPOSITES:-50558}:50052"
    environment:
      - ANSYSLMD_LICENSE_FILE=${ANSYSLMD_LICENSE_FILE}
    working_dir: /home/container/workdir
    volumes:
      - "acp_data:/home/container/workdir/"

volumes:
  acp_data:
