version: '3.8'
services:
  acp-grpc-server:
    restart: unless-stopped
    image: ${IMAGE_NAME_PYACP:-ghcr.io/ansys-internal/pyacp:latest}
    command: ["${PYACP_DELAY:-100ms}", "${PYACP_RATE:-1mbit}", "--server-address=0.0.0.0:50051"]
    environment:
      - ANSYSLMD_LICENSE_FILE=${ANSYSLMD_LICENSE_FILE}
    ports:
      - "${PORT_PYACP:-50555}:50051"
    working_dir: /home/container/workdir
    volumes:
      - "acp_data:/home/container/workdir/"
    user: "1000:1000"
    cap_add:
      - NET_ADMIN
  ansys-tools-filetransfer:
    restart: unless-stopped
    image: ${IMAGE_NAME_FILETRANSFER:-ghcr.io/ansys/tools-filetransfer:latest}
    ports:
      - "${PORT_FILETRANSFER:-50556}:50000"
    working_dir: /home/container/workdir
    volumes:
      - "acp_data:/home/container/workdir/"
    user: "1000:1000"

volumes:
  acp_data:
