# Copyright (C) 2022 - 2026 Synopsys, Inc. and ANSYS, Inc. All rights reserved.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

__all__ = ["ImportObjectMixin"]

from ansys.api.acp.v0.import_object_pb2 import (
    DeleteGeneratedObjectsRequest,
    ListGeneratedObjectsReply,
    ListGeneratedObjectsRequest,
    RunRequest,
)

from .._utils.property_protocols import ReadOnlyProperty
from ._grpc_helpers.exceptions import wrap_grpc_errors
from ._grpc_helpers.polymorphic_from_pb import tree_object_from_resource_path
from ._grpc_helpers.property_helper import grpc_data_property_read_only, mark_grpc_properties
from .base import CreatableTreeObject


@mark_grpc_properties
class ImportObjectMixin(CreatableTreeObject):
    """Mixin class for import objects."""

    has_run: ReadOnlyProperty[bool] = grpc_data_property_read_only("properties.has_run")

    def run(self) -> None:
        """Run the import object using the stored settings.

        Previously generated objects are deleted before running the import object.
        """
        with wrap_grpc_errors():
            self._get_stub().Run(RunRequest(resource_path=self._resource_path))  # type: ignore

    def list_generated_objects(self) -> list[CreatableTreeObject]:
        """List all entities generated by this import."""
        with wrap_grpc_errors():
            response: ListGeneratedObjectsReply = self._get_stub().ListGeneratedObjects(  # type: ignore
                ListGeneratedObjectsRequest(resource_path=self._resource_path)
            )
            generated_objects = [
                tree_object_from_resource_path(obj, server_wrapper=self._server_wrapper)
                for obj in response.generated_objects
            ]
            assert None not in generated_objects, "Failed to create tree object from resource path."
            return generated_objects  # type: ignore

    def delete_generated_objects(self) -> None:
        """Delete all entities generated by this import."""
        with wrap_grpc_errors():
            self._get_stub().DeleteGeneratedObjects(  # type: ignore
                DeleteGeneratedObjectsRequest(resource_path=self._resource_path)
            )
