{
 "title": "acp-dashboard-1",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Informational Messages",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{level=~\"INFO\"} | json | line_format `{{.body}}`"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{level=~\"WARN\"} | json | line_format `{{.body}}`"
    }
   ]
  },
  {
   "title": "Debug Messages",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{level=~\"DEBUG\"} | json | line_format `{{.body}}`"
    }
   ]
  },
  {
   "title": "Log Level Time Series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({service_name=\"acp-grpcserver\"} |= `` | line_format `{{.severity}}` [$__interval])"
    }
   ]
  },
  {
   "title": "Materials-Create Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "limit": 20, "serviceName": "acp-grpcserver", "spanName": "materials:Create" }
   ]
  },
  {
   "title": "Model API call rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(acp_model_api_counter_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}