import importlib.metadata

from ._client import Client
from ._server import DirectLaunchConfig, DockerComposeLaunchConfig, LaunchMode, launch_acp
from ._tree_objects import (
    AnalysisPly,
    BooleanSelectionRule,
    CylindricalSelectionRule,
    EdgeSet,
    EdgeSetType,
    ElementalDataType,
    ElementSet,
    Fabric,
    FabricWithAngle,
    Lamina,
    LinkedSelectionRule,
    LookUpTable1D,
    LookUpTable1DColumn,
    LookUpTable3D,
    LookUpTable3DColumn,
    Material,
    Model,
    ModelingGroup,
    ModelingPly,
    NodalDataType,
    OrientedSelectionSet,
    ParallelSelectionRule,
    ProductionPly,
    Rosette,
    Sensor,
    SphericalSelectionRule,
    Stackup,
    SubLaminate,
    TubeSelectionRule,
    UnitSystemType,
    VariableOffsetSelectionRule,
)

__version__ = importlib.metadata.version(__name__.replace(".", "-"))


__all__ = [
    "__version__",
    "launch_acp",
    "LaunchMode",
    "DirectLaunchConfig",
    "DockerComposeLaunchConfig",
    "Client",
    "Model",
    "Material",
    "Fabric",
    "SubLaminate",
    "ElementSet",
    "EdgeSet",
    "EdgeSetType",
    "Rosette",
    "LookUpTable1D",
    "LookUpTable1DColumn",
    "LookUpTable3D",
    "LookUpTable3DColumn",
    "ParallelSelectionRule",
    "CylindricalSelectionRule",
    "SphericalSelectionRule",
    "TubeSelectionRule",
    "VariableOffsetSelectionRule",
    "BooleanSelectionRule",
    "LinkedSelectionRule",
    "OrientedSelectionSet",
    "ModelingGroup",
    "ModelingPly",
    "ProductionPly",
    "AnalysisPly",
    "UnitSystemType",
    "Stackup",
    "FabricWithAngle",
    "ElementalDataType",
    "NodalDataType",
]
