# check spelling, codestyle
name: GitHub CI

# run only on main branch.  This avoids duplicated actions on PRs
on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main
  workflow_dispatch:

jobs:
  style:
    name: Pre-commit Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install pre-commit requirements
        run: |
          git config --global url."https://${{ secrets.PYANSYS_CI_BOT_TOKEN }}@github.com/ansys/ansys-api-acp-private".insteadOf "https://github.com/ansys/ansys-api-acp-private"
          pip install poetry
          poetry install -E pre-commit

      - name: Run pre-commit
        run: |
          poetry run pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )

  main:
    name: Build and Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.9', '3.10']

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create source and wheel packages
        run: |
          git config --global url."https://${{ secrets.PYANSYS_CI_BOT_TOKEN }}@github.com/ansys/ansys-api-acp-private".insteadOf "https://github.com/ansys/ansys-api-acp-private"
          pip install poetry
          poetry build

      - name: Validate packages
        run: |
          pip install twine
          twine check dist/*

      - name: Install library, with test extra
        run: pip install $(echo dist/*.whl)[test]

      - name: Login in Github Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: pyansys-ci-bot
          password: ${{ secrets.PYANSYS_CI_BOT_PACKAGE_TOKEN }}

      - name: Unit testing
        working-directory: tests
        run: |
          docker pull ghcr.io/pyansys/pyacp-private:latest
          pytest -v --license-server=1055@$LICENSE_SERVER --no-server-log-files
        env:
          LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}

      - name: Upload wheel
        uses: actions/upload-artifact@v2
        with:
          name: ansys-acp-core-wheel
          path: dist/
          retention-days: 7

  docs:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install library, with docs extra
        run: |
          git config --global url."https://${{ secrets.PYANSYS_CI_BOT_TOKEN }}@github.com/ansys/ansys-api-acp-private".insteadOf "https://github.com/ansys/ansys-api-acp-private"
          pip install poetry
          poetry install -E docs

      - name: Build HTML
        run: |
          poetry run make -C doc html SPHINXOPTS="-W --keep-going"
          touch doc/build/html/.nojekyll
          echo "dev.acp.docs.pyansys.com" >> doc/build/html/CNAME

      - name: Upload HTML Documentation
        uses: actions/upload-artifact@v2
        with:
          name: Documentation-html
          path: doc/build/html
          retention-days: 7

      - name: Deploy Documentation
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: doc/build/html
          clean: true


  # Release:
  #   if: contains(github.ref, 'refs/tags')
  #   needs: [main, style, docs]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up Python
  #       uses: actions/setup-python@v1
  #       with:
  #         python-version: 3.9

  #     - uses: actions/checkout@v3

  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: ansys-acp-core-wheel

  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: Documentation-pdf

  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: Documentation-html
  #         path: ~/html

  #     # list current directory
  #     - name: List directory structure
  #       run: ls -R

  #     - name: Deploy
  #       uses: JamesIves/github-pages-deploy-action@4.1.5
  #       with:
  #         BRANCH: gh-pages
  #         FOLDER: ~/html
  #         CLEAN: true

  #     # note how we use the PyPI tokens
  #     - name: Upload to Azure PyPi (disabled)
  #       run: |
  #         pip install twine
  #         # twine upload --skip-existing ./**/*.whl
  #       env:
  #         TWINE_USERNAME: __token__
  #         TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}

  #     - name: Release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         files: |
  #           ./**/*.whl
  #           ./**/*.zip
  #           ./**/*.pdf
