name: Nightly test from wheel

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
concurrency:
  group: nightly-test
  cancel-in-progress: true
permissions:
  contents: read
  packages: read # needed for pulling the Docker image
env:
  UV_FROZEN: "true"

jobs:
  main:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13', '3.14']
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create wheel
        run: |
          uv build --wheel

      - name: Install library from wheel, test dependencies from uv.lock
        run: |
          python -m venv test_env
          . test_env/bin/activate

          pip install $(echo dist/*.whl)[graphics]
          uv export --group test --no-emit-project --output-file requirements-test.txt
          pip install -r requirements-test.txt

      - name: Login in Github Container registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: pyansys-ci-bot
          password: ${{ secrets.PYANSYS_CI_BOT_PACKAGE_TOKEN }}

      - name: Unit testing
        run: |
          docker pull $IMAGE_NAME
          . test_env/bin/activate
          pytest -v --license-server=1055@$LICENSE_SERVER --no-server-log-files tests/unittests
        env:
          LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}
          IMAGE_NAME: 'ghcr.io/ansys/acp:latest'
