name: Nightly test from wheel

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
concurrency:
  group: nightly-test
  cancel-in-progress: true
permissions:
  contents: read
  packages: read # needed for pulling the Docker image
env:
  UV_FROZEN: "true"

jobs:
  main:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13', '3.14']
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create wheel
        run: |
          uv build --wheel

      - name: Install library from wheel, test dependencies from uv.lock
        run: |
          python -m venv test_env
          . test_env/bin/activate

          pip install $(echo dist/*.whl)[graphics]
          uv export --group test --no-emit-project --output-file requirements-test.txt
          pip install -r requirements-test.txt

      - name: Login in Github Container registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: pyansys-ci-bot
          password: ${{ secrets.PYANSYS_CI_BOT_PACKAGE_TOKEN }}

      - name: Unit testing
        run: |
          docker pull $IMAGE_NAME
          . test_env/bin/activate
          pytest -v --license-server=1055@$LICENSE_SERVER --no-server-log-files tests/unittests
        env:
          LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}
          IMAGE_NAME: 'ghcr.io/ansys/acp:latest'
